### PR TITLE
Add boolean expressions

### PR DESCRIPTION
**Pull request by oakmac**
Adds support for boolean expressions.

### CODE REVIEW

**Comment by cburgmer** [comment]
Thanks a lot for this PR. I could help merge this and probably also release a new version.

One finding though:

The current change drops expression type `:some` in favour of a unified approach via `:bool` (https://github.com/gga/json-path/pull/16/files#diff-2c31ef4ff938be34b3e1196e8061a1ca38708313bd77838e6e2a3e927d21c2a4L13). This affects `$[?(@.keyWithFalsyValue)]`.

There is an active Working Group pushing towards a common JSONPath standard. Their current version has this to say about the above case (https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#name-filter-selector):

> A member or element value by itself in a Boolean context is interpreted as false only if it does not exist. Otherwise it is interpreted as true.

Not everybody seems to agree with that (e.g. https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/180), but in the light of the current proposal I would prefer if we didn't change the existing behaviour, which also would minimise the impact on current dependents.

**Comment by cburgmer** [comment]
I just updated the regression test suite in 25faef58c94a78c238a7dd0d35c0d1744df730e2 (introducing no merge conflict). They can be a bit terse, but will give you a good idea on the wider impact of your changes. 

The regression test which flags the issue I mention above is the following:

```
Warning: implementation has changed for filter_expression_with_value: $[?(@.key)] (previous status open)
Old:
  [#ordered/map ([:key true]) #ordered/map ([:key false]) #ordered/map ([:key "value"]) #ordered/map ([:key ""]) #ordered/map ([:key 0]) #ordered/map ([:key 1]) #ordered/map ([:key -1]) #ordered/map ([:key 42]) #ordered/map ([:key #ordered/map nil]) #ordered/map ([:key []])]
New:
  (#ordered/map ([:key true]) #ordered/map ([:key "value"]) #ordered/map ([:key ""]) #ordered/map ([:key 0]) #ordered/map ([:key 1]) #ordered/map ([:key -1]) #ordered/map ([:key 42]) #ordered/map ([:key #ordered/map nil]) #ordered/map ([:key []]))
```

The whole result in the JSONPath Comparison project would be that one: https://cburgmer.github.io/json-path-comparison/#filter_expression_with_value

**Comment by oakmac** [comment]
> Thanks a lot for this PR. I could help merge this and probably also release a new version.

Ok - great!

> The current change drops expression type :some in favour of a unified approach via :bool

Yes - I was aware this was making a change. I thought the scope was limited to just the internal parsed data structure, but your explanation / that thread makes sense. Thank you for updating the test suite.

I will give this a think and see if I can't get everything to pass with the updated tests.

**Comment by oakmac** [comment]
@cburgmer I updated to keep the old behavior (keeping `:some` and totally removed `:bool`)

Everything passes when I run the test suite, and I do see many examples of `Warning: implementation has changed for <example>`.

I assume the reference file `Clojure_json-path.yaml` needs to be updated to reflect the new status of the library? I am not sure how to do that, and honestly prefer if someone else does it so there are more eyeballs to catch errors 😜

**Comment by cburgmer** [comment]
Thanks. Looks good!

The regression tests are a bit tricky. They fail for results not matching the consensus, but if no consensus exists will spit out warnings only.

I can update the reference. As this is generated by the Comparison Project it needs a new release first though.

**Pull request merged**
